auth_controllers:
    resource:
        path: ../src/Auth/Infrastructure/Controller/
        namespace: App\Auth\Infrastructure\Controller
    type: attribute

categories_controllers:
    resource:
        path: ../src/Categories/Infrastructure/Controller/
        namespace: App\Categories\Infrastructure\Controller
    type: attribute

geostories_controllers:
    resource:
        path: ../src/GeoStories/Infrastructure/Controller/
        namespace: App\GeoStories\Infrastructure\Controller
    type: attribute

influencers_controllers:
    resource:
        path: ../src/Influencers/Infrastructure/Controller/
        namespace: App\Influencers\Infrastructure\Controller
    type: attribute

businesses_controllers:
    resource:
        path: ../src/Business/Infrastructure/Controller/
        namespace: App\Business\Infrastructure\Controller
    type: attribute

products_controllers:
    resource:
        path: ../src/Products/Infrastructure/Controller/
        namespace: App\Products\Infrastructure\Controller
    type: attribute

billing_controllers:
    resource:
        path: ../src/Billing/Infrastructure/Controller/
        namespace: App\Billing\Infrastructure\Controller
    type: attribute

follows_controllers:
    resource:
        path: ../src/Follows/Infrastructure/Controller/
        namespace: App\Follows\Infrastructure\Controller
    type: attribute

account_controllers:
    resource:
        path: ../src/Account/Infrastructure/Controller/
        namespace: App\Account\Infrastructure\Controller
    type: attribute
